### ISSUE TITLE
Can use for api 14+?

### ISSUE THREAD

**Issue by tellfa** [marcoscgdev/shortcut-helper#1]
Can i use this library in android 14+?

**Comment by marcoscgdev** [comment]
Of course, this library is compatible on API 9+ devices.

**Comment by tellfa** [comment]
and show in real device from android 4+ or just show and 7+?

**Comment by marcoscgdev** [comment]
It only shows on Android 7.1+ because it's an Android 7.1 feature

**Comment by marcoscgdev** [comment]
If you have any doubt you can write to my email marcoscgdev@gmail.com
