### ISSUE TITLE
Seems to be for Android 7.1, not 7.0

### ISSUE THREAD

**Issue by DonManfred** [marcoscgdev/shortcut-helper#2]
The App crashes on my S7 EDGE using Android 7.0.1

**Comment by marcoscgdev** [comment]
Yeah, app shortcuts are a 7.1 Android feature :)

It was my mistake to indicate 7.0 in the description

But the app would not have to close

Edit: I find the error. I'm going to update the library now. Thanks for your notice 👍

**Comment by marcoscgdev** [comment]
New version available! Check it out 😄
